#!/usr/bin/env python

import rospy
import sympy as sym
import numpy as np
from numpy import *
from sympy import *
from sensor_msgs.msg import JointState

## ARM_TRAJ NODE ##
'''
The arm_traj node uses inverse kinematics to publish joint states to the robot arm defined in the twoarm.urdf.xacro file and
make its end effector follow a linear path.

Publishers:
    Name: joint_states Type: sensor_msgs/JointState ~ Publishes joint positions to each joint in the robot arm

Parameters: 
    Name: L1 File: arm.yaml ~ Length of first link
    Name: L2 File: arm.yaml ~ Lenght of second link
    Name: R1 File: arm.yaml ~ Radius of first link
    Name: R2 File: arm.yaml ~ Radius of second link
    Name: T File: arm.yaml ~ Period of arm movement cycle
'''

def main():
    '''
    Continuously updates the target position of the end effector with a time variable and the given x and y equations,
    uses the inverse kinematics equations to calculate the joint position of each joint, and finally publishes
    the joint information to JointState.
    '''
    while not rospy.is_shutdown():
        pub = rospy.Publisher('joint_states', JointState, queue_size = 10)
        
        joints = JointState() 

        t = rospy.get_time()

        L1 = rospy.get_param("L1")
        L2 = rospy.get_param("L2")
        T = rospy.get_param("T")

        h = 2*(L1 + L2)/3

        x = 0.9*cos((2*pi*t)/T)*sqrt((L1+L2)**2-h**2)
        y = 2*(L1+L2)/3

        beta = acos((L1**2+L2**2-x**2-y**2)/(2*L1*L2))

        alpha = acos((x**2+y**2+L1**2-L2**2)/(2*L1*sqrt(x**2+y**2)))

        g = atan2(y,x)

        theta1 = g - alpha

        theta2 = pi - beta
        
        joints.header.stamp = rospy.Time.now() 
        joints.name = ['joint_1', 'joint_2']
        joints.position = [theta1,theta2]
        joints.velocity = [0,0]
        joints.effort = [0,0]

        pub.publish(joints)

if __name__ == '__main__':
    rospy.init_node('arm_traj')
    main()    
    rospy.spin()